import { Card } from 'flowbite-react';
import Head from 'next/head';
import { useContext } from 'react';
import { FirebaseContext } from '../lib/context';

export default function Home() {
  const { user, loadingUser } = useContext(FirebaseContext);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-sm">
        <h1>You are logged in: {user?.displayName}</h1>
      </div>
    </div>
  );
}
